// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package sms

import (
	"UniApi/api/sms"
)

type ControllerV1 struct{}

func NewV1() sms.ISmsV1 {
	return &ControllerV1{}
}
