// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"UniApi/internal/dao/internal"
)

// internalNmcPicsDao is internal type for wrapping internal DAO implements.
type internalNmcPicsDao = *internal.NmcPicsDao

// nmcPicsDao is the data access object for table pics.
// You can define custom methods on it to extend its functionality as you wish.
type nmcPicsDao struct {
	internalNmcPicsDao
}

var (
	// NmcPics is globally public accessible object for table pics operations.
	NmcPics = nmcPicsDao{
		internal.NewNmcPicsDao(),
	}
)

// Fill with you ideas below.
