// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"UniApi/internal/dao/internal"
)

// internalNmcBbuRoleDao is internal type for wrapping internal DAO implements.
type internalNmcBbuRoleDao = *internal.NmcBbuRoleDao

// nmcBbuRoleDao is the data access object for table bbu_role.
// You can define custom methods on it to extend its functionality as you wish.
type nmcBbuRoleDao struct {
	internalNmcBbuRoleDao
}

var (
	// NmcBbuRole is globally public accessible object for table bbu_role operations.
	NmcBbuRole = nmcBbuRoleDao{
		internal.NewNmcBbuRoleDao(),
	}
)

// Fill with you ideas below.
