// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"UniApi/internal/dao/internal"
)

// internalNmcNmcPhotoDao is internal type for wrapping internal DAO implements.
type internalNmcNmcPhotoDao = *internal.NmcNmcPhotoDao

// nmcNmcPhotoDao is the data access object for table nmc_photo.
// You can define custom methods on it to extend its functionality as you wish.
type nmcNmcPhotoDao struct {
	internalNmcNmcPhotoDao
}

var (
	// NmcNmcPhoto is globally public accessible object for table nmc_photo operations.
	NmcNmcPhoto = nmcNmcPhotoDao{
		internal.NewNmcNmcPhotoDao(),
	}
)

// Fill with you ideas below.
