// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"UniApi/internal/dao/internal"
)

// internalNmcNmcDesignDao is internal type for wrapping internal DAO implements.
type internalNmcNmcDesignDao = *internal.NmcNmcDesignDao

// nmcNmcDesignDao is the data access object for table nmc_design.
// You can define custom methods on it to extend its functionality as you wish.
type nmcNmcDesignDao struct {
	internalNmcNmcDesignDao
}

var (
	// NmcNmcDesign is globally public accessible object for table nmc_design operations.
	NmcNmcDesign = nmcNmcDesignDao{
		internal.NewNmcNmcDesignDao(),
	}
)

// Fill with you ideas below.
