// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"UniApi/internal/dao/internal"
)

// internalNmcWorkDao is internal type for wrapping internal DAO implements.
type internalNmcWorkDao = *internal.NmcWorkDao

// nmcWorkDao is the data access object for table work.
// You can define custom methods on it to extend its functionality as you wish.
type nmcWorkDao struct {
	internalNmcWorkDao
}

var (
	// NmcWork is globally public accessible object for table work operations.
	NmcWork = nmcWorkDao{
		internal.NewNmcWorkDao(),
	}
)

// Fill with you ideas below.
