// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"UniApi/internal/dao/internal"
)

// internalNmcTopicDao is internal type for wrapping internal DAO implements.
type internalNmcTopicDao = *internal.NmcTopicDao

// nmcTopicDao is the data access object for table topic.
// You can define custom methods on it to extend its functionality as you wish.
type nmcTopicDao struct {
	internalNmcTopicDao
}

var (
	// NmcTopic is globally public accessible object for table topic operations.
	NmcTopic = nmcTopicDao{
		internal.NewNmcTopicDao(),
	}
)

// Fill with you ideas below.
