// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"UniApi/internal/dao/internal"
)

// internalNmcCommentDao is internal type for wrapping internal DAO implements.
type internalNmcCommentDao = *internal.NmcCommentDao

// nmcCommentDao is the data access object for table comment.
// You can define custom methods on it to extend its functionality as you wish.
type nmcCommentDao struct {
	internalNmcCommentDao
}

var (
	// NmcComment is globally public accessible object for table comment operations.
	NmcComment = nmcCommentDao{
		internal.NewNmcCommentDao(),
	}
)

// Fill with you ideas below.
