// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"UniApi/internal/dao/internal"
)

// internalNmcSmsDao is internal type for wrapping internal DAO implements.
type internalNmcSmsDao = *internal.NmcSmsDao

// nmcSmsDao is the data access object for table sms.
// You can define custom methods on it to extend its functionality as you wish.
type nmcSmsDao struct {
	internalNmcSmsDao
}

var (
	// NmcSms is globally public accessible object for table sms operations.
	NmcSms = nmcSmsDao{
		internal.NewNmcSmsDao(),
	}
)

// Fill with you ideas below.
